# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '6view_design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1965, 930)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_open_image = QtWidgets.QPushButton(self.frame_3)
        self.btn_open_image.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_open_image.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/Load_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_open_image.setIcon(icon)
        self.btn_open_image.setIconSize(QtCore.QSize(30, 30))
        self.btn_open_image.setObjectName("btn_open_image")
        self.horizontalLayout_5.addWidget(self.btn_open_image)
        self.btn_open_video = QtWidgets.QPushButton(self.frame_3)
        self.btn_open_video.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_open_video.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/Load_video.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_open_video.setIcon(icon1)
        self.btn_open_video.setIconSize(QtCore.QSize(35, 30))
        self.btn_open_video.setObjectName("btn_open_video")
        self.horizontalLayout_5.addWidget(self.btn_open_video)
        self.btn_open_camera = QtWidgets.QPushButton(self.frame_3)
        self.btn_open_camera.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_open_camera.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/Load_camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_open_camera.setIcon(icon2)
        self.btn_open_camera.setIconSize(QtCore.QSize(30, 30))
        self.btn_open_camera.setObjectName("btn_open_camera")
        self.horizontalLayout_5.addWidget(self.btn_open_camera)
        self.btn_save_image = QtWidgets.QPushButton(self.frame_3)
        self.btn_save_image.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_save_image.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/Save_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save_image.setIcon(icon3)
        self.btn_save_image.setIconSize(QtCore.QSize(40, 30))
        self.btn_save_image.setObjectName("btn_save_image")
        self.horizontalLayout_5.addWidget(self.btn_save_image)
        self.btn_Record_video = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Record_video.sizePolicy().hasHeightForWidth())
        self.btn_Record_video.setSizePolicy(sizePolicy)
        self.btn_Record_video.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_Record_video.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/Record_start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Record_video.setIcon(icon4)
        self.btn_Record_video.setIconSize(QtCore.QSize(30, 30))
        self.btn_Record_video.setCheckable(True)
        self.btn_Record_video.setObjectName("btn_Record_video")
        self.horizontalLayout_5.addWidget(self.btn_Record_video)
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.btn_rotate_left = QtWidgets.QPushButton(self.frame_3)
        self.btn_rotate_left.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_rotate_left.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/Rotate_left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_rotate_left.setIcon(icon5)
        self.btn_rotate_left.setIconSize(QtCore.QSize(40, 30))
        self.btn_rotate_left.setObjectName("btn_rotate_left")
        self.horizontalLayout_5.addWidget(self.btn_rotate_left)
        self.btn_rotate_right = QtWidgets.QPushButton(self.frame_3)
        self.btn_rotate_right.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_rotate_right.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/Rotate_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_rotate_right.setIcon(icon6)
        self.btn_rotate_right.setIconSize(QtCore.QSize(40, 30))
        self.btn_rotate_right.setObjectName("btn_rotate_right")
        self.horizontalLayout_5.addWidget(self.btn_rotate_right)
        self.line_4 = QtWidgets.QFrame(self.frame_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_5.addWidget(self.line_4)
        self.btn_zoom_in = QtWidgets.QPushButton(self.frame_3)
        self.btn_zoom_in.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_zoom_in.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icon/Zoom_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_zoom_in.setIcon(icon7)
        self.btn_zoom_in.setIconSize(QtCore.QSize(40, 30))
        self.btn_zoom_in.setObjectName("btn_zoom_in")
        self.horizontalLayout_5.addWidget(self.btn_zoom_in)
        self.btn_zoom_out = QtWidgets.QPushButton(self.frame_3)
        self.btn_zoom_out.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_zoom_out.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icon/Zoom_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_zoom_out.setIcon(icon8)
        self.btn_zoom_out.setIconSize(QtCore.QSize(40, 30))
        self.btn_zoom_out.setObjectName("btn_zoom_out")
        self.horizontalLayout_5.addWidget(self.btn_zoom_out)
        self.coombo_zoom = QtWidgets.QComboBox(self.frame_3)
        self.coombo_zoom.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(12)
        self.coombo_zoom.setFont(font)
        self.coombo_zoom.setObjectName("coombo_zoom")
        self.coombo_zoom.addItem("")
        self.coombo_zoom.addItem("")
        self.coombo_zoom.addItem("")
        self.coombo_zoom.addItem("")
        self.coombo_zoom.addItem("")
        self.coombo_zoom.addItem("")
        self.coombo_zoom.addItem("")
        self.coombo_zoom.addItem("")
        self.horizontalLayout_5.addWidget(self.coombo_zoom)
        self.line_3 = QtWidgets.QFrame(self.frame_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_5.addWidget(self.line_3)
        self.label_camera = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_camera.sizePolicy().hasHeightForWidth())
        self.label_camera.setSizePolicy(sizePolicy)
        self.label_camera.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(14)
        self.label_camera.setFont(font)
        self.label_camera.setStyleSheet("")
        self.label_camera.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_camera.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_camera.setAlignment(QtCore.Qt.AlignCenter)
        self.label_camera.setObjectName("label_camera")
        self.horizontalLayout_5.addWidget(self.label_camera)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(1400, 0))
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Panel)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1398, 512))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_Original_image = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Original_image.sizePolicy().hasHeightForWidth())
        self.label_Original_image.setSizePolicy(sizePolicy)
        self.label_Original_image.setMinimumSize(QtCore.QSize(1380, 0))
        # self.label_Original_image.setMaximumSize(QtCore.QSize(200, 16777215))
        # self.label_Original_image.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Original_image.setText("")
        self.label_Original_image.setObjectName("label_Original_image")
        self.horizontalLayout_7.addWidget(self.label_Original_image, 0, QtCore.Qt.AlignHCenter)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: #71D1BA;   \n"
"border-radius: 10px;")
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_5.addWidget(self.listWidget)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.title_image_ori = QtWidgets.QLabel(self.frame_2)
        self.title_image_ori.setMinimumSize(QtCore.QSize(340, 40))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(16)
        self.title_image_ori.setFont(font)
        self.title_image_ori.setStyleSheet("background-color: #71D1BA;   \n"
"border-radius: 10px;")
        self.title_image_ori.setFrameShape(QtWidgets.QFrame.Box)
        self.title_image_ori.setAlignment(QtCore.Qt.AlignCenter)
        self.title_image_ori.setObjectName("title_image_ori")
        self.horizontalLayout_3.addWidget(self.title_image_ori)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMinimumSize(QtCore.QSize(200, 200))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1945, 199))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_image2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_image2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image2.setText("")
        self.label_image2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image2.setObjectName("label_image2")
        self.gridLayout.addWidget(self.label_image2, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setFrameShape(QtWidgets.QFrame.Box)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_image1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_image1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image1.setText("")
        self.label_image1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image1.setObjectName("label_image1")
        self.gridLayout.addWidget(self.label_image1, 1, 0, 1, 1)
        self.label_image3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_image3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image3.setText("")
        self.label_image3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image3.setObjectName("label_image3")
        self.gridLayout.addWidget(self.label_image3, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_image5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_image5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image5.setText("")
        self.label_image5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image5.setObjectName("label_image5")
        self.gridLayout.addWidget(self.label_image5, 5, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_image4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_image4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image4.setText("")
        self.label_image4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image4.setObjectName("label_image4")
        self.gridLayout.addWidget(self.label_image4, 5, 0, 1, 1)
        self.label_image6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_image6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image6.setText("")
        self.label_image6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image6.setObjectName("label_image6")
        self.gridLayout.addWidget(self.label_image6, 5, 2, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout.addWidget(self.scrollArea_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_view = QtWidgets.QFrame(self.centralwidget)
        self.frame_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_view.setObjectName("frame_view")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_view)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_ori_view = QtWidgets.QPushButton(self.frame_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ori_view.sizePolicy().hasHeightForWidth())
        self.btn_ori_view.setSizePolicy(sizePolicy)
        self.btn_ori_view.setMinimumSize(QtCore.QSize(60, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(12)
        self.btn_ori_view.setFont(font)
        self.btn_ori_view.setCheckable(True)
        self.btn_ori_view.setObjectName("btn_ori_view")
        self.horizontalLayout_4.addWidget(self.btn_ori_view)
        self.btn_6view = QtWidgets.QPushButton(self.frame_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_6view.sizePolicy().hasHeightForWidth())
        self.btn_6view.setSizePolicy(sizePolicy)
        self.btn_6view.setMinimumSize(QtCore.QSize(60, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(12)
        self.btn_6view.setFont(font)
        self.btn_6view.setCheckable(True)
        self.btn_6view.setObjectName("btn_6view")
        self.horizontalLayout_4.addWidget(self.btn_6view)
        self.btn_view_1 = QtWidgets.QPushButton(self.frame_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_view_1.sizePolicy().hasHeightForWidth())
        self.btn_view_1.setSizePolicy(sizePolicy)
        self.btn_view_1.setMinimumSize(QtCore.QSize(60, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(12)
        self.btn_view_1.setFont(font)
        self.btn_view_1.setCheckable(True)
        self.btn_view_1.setObjectName("btn_view_1")
        self.horizontalLayout_4.addWidget(self.btn_view_1)
        self.btn_view_2 = QtWidgets.QPushButton(self.frame_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_view_2.sizePolicy().hasHeightForWidth())
        self.btn_view_2.setSizePolicy(sizePolicy)
        self.btn_view_2.setMinimumSize(QtCore.QSize(60, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(12)
        self.btn_view_2.setFont(font)
        self.btn_view_2.setCheckable(True)
        self.btn_view_2.setObjectName("btn_view_2")
        self.horizontalLayout_4.addWidget(self.btn_view_2)
        self.btn_view_3 = QtWidgets.QPushButton(self.frame_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_view_3.sizePolicy().hasHeightForWidth())
        self.btn_view_3.setSizePolicy(sizePolicy)
        self.btn_view_3.setMinimumSize(QtCore.QSize(60, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(12)
        self.btn_view_3.setFont(font)
        self.btn_view_3.setCheckable(True)
        self.btn_view_3.setObjectName("btn_view_3")
        self.horizontalLayout_4.addWidget(self.btn_view_3)
        self.btn_view_4 = QtWidgets.QPushButton(self.frame_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_view_4.sizePolicy().hasHeightForWidth())
        self.btn_view_4.setSizePolicy(sizePolicy)
        self.btn_view_4.setMinimumSize(QtCore.QSize(60, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(12)
        self.btn_view_4.setFont(font)
        self.btn_view_4.setCheckable(True)
        self.btn_view_4.setObjectName("btn_view_4")
        self.horizontalLayout_4.addWidget(self.btn_view_4)
        self.btn_view_5 = QtWidgets.QPushButton(self.frame_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_view_5.sizePolicy().hasHeightForWidth())
        self.btn_view_5.setSizePolicy(sizePolicy)
        self.btn_view_5.setMinimumSize(QtCore.QSize(60, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(12)
        self.btn_view_5.setFont(font)
        self.btn_view_5.setCheckable(True)
        self.btn_view_5.setObjectName("btn_view_5")
        self.horizontalLayout_4.addWidget(self.btn_view_5)
        self.btn_view_6 = QtWidgets.QPushButton(self.frame_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_view_6.sizePolicy().hasHeightForWidth())
        self.btn_view_6.setSizePolicy(sizePolicy)
        self.btn_view_6.setMinimumSize(QtCore.QSize(60, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(12)
        self.btn_view_6.setFont(font)
        self.btn_view_6.setCheckable(True)
        self.btn_view_6.setObjectName("btn_view_6")
        self.horizontalLayout_4.addWidget(self.btn_view_6)
        self.horizontalLayout.addWidget(self.frame_view)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_prev_video = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_prev_video.sizePolicy().hasHeightForWidth())
        self.btn_prev_video.setSizePolicy(sizePolicy)
        self.btn_prev_video.setMinimumSize(QtCore.QSize(40, 30))
        self.btn_prev_video.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icon/Rewind.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_prev_video.setIcon(icon9)
        self.btn_prev_video.setIconSize(QtCore.QSize(30, 30))
        self.btn_prev_video.setObjectName("btn_prev_video")
        self.horizontalLayout_6.addWidget(self.btn_prev_video)
        self.btn_play_pouse = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_play_pouse.sizePolicy().hasHeightForWidth())
        self.btn_play_pouse.setSizePolicy(sizePolicy)
        self.btn_play_pouse.setMinimumSize(QtCore.QSize(40, 30))
        self.btn_play_pouse.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icon/Play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_play_pouse.setIcon(icon10)
        self.btn_play_pouse.setIconSize(QtCore.QSize(30, 30))
        self.btn_play_pouse.setObjectName("btn_play_pouse")
        self.horizontalLayout_6.addWidget(self.btn_play_pouse)
        self.btn_stop_video = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_stop_video.sizePolicy().hasHeightForWidth())
        self.btn_stop_video.setSizePolicy(sizePolicy)
        self.btn_stop_video.setMinimumSize(QtCore.QSize(40, 30))
        self.btn_stop_video.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icon/Stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_stop_video.setIcon(icon11)
        self.btn_stop_video.setIconSize(QtCore.QSize(30, 30))
        self.btn_stop_video.setObjectName("btn_stop_video")
        self.horizontalLayout_6.addWidget(self.btn_stop_video)
        self.btn_skip_video = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_skip_video.sizePolicy().hasHeightForWidth())
        self.btn_skip_video.setSizePolicy(sizePolicy)
        self.btn_skip_video.setMinimumSize(QtCore.QSize(40, 30))
        self.btn_skip_video.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icon/Forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_skip_video.setIcon(icon12)
        self.btn_skip_video.setIconSize(QtCore.QSize(30, 30))
        self.btn_skip_video.setObjectName("btn_skip_video")
        self.horizontalLayout_6.addWidget(self.btn_skip_video)
        self.label_time_recent = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_recent.sizePolicy().hasHeightForWidth())
        self.label_time_recent.setSizePolicy(sizePolicy)
        self.label_time_recent.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(14)
        self.label_time_recent.setFont(font)
        self.label_time_recent.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_recent.setObjectName("label_time_recent")
        self.horizontalLayout_6.addWidget(self.label_time_recent)
        self.slider_Video = QtWidgets.QSlider(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_Video.sizePolicy().hasHeightForWidth())
        self.slider_Video.setSizePolicy(sizePolicy)
        self.slider_Video.setOrientation(QtCore.Qt.Horizontal)
        self.slider_Video.setObjectName("slider_Video")
        self.horizontalLayout_6.addWidget(self.slider_Video)
        self.label_time_end = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_end.sizePolicy().hasHeightForWidth())
        self.label_time_end.setSizePolicy(sizePolicy)
        self.label_time_end.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(14)
        self.label_time_end.setFont(font)
        self.label_time_end.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_end.setObjectName("label_time_end")
        self.horizontalLayout_6.addWidget(self.label_time_end)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1965, 28))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(14)
        font.setUnderline(True)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(12)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(12)
        self.menuHelp.setFont(font)
        self.menuHelp.setObjectName("menuHelp")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_Image = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icon/Load_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Image.setIcon(icon13)
        self.actionOpen_Image.setObjectName("actionOpen_Image")
        self.actionLoad_Video = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icon/Load_video.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_Video.setIcon(icon14)
        self.actionLoad_Video.setObjectName("actionLoad_Video")
        self.actionOpen_Camera = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icon/Load_camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Camera.setIcon(icon15)
        self.actionOpen_Camera.setObjectName("actionOpen_Camera")
        self.actionCam_parameter = QtWidgets.QAction(MainWindow)
        self.actionCam_parameter.setObjectName("actionCam_parameter")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout_Us = QtWidgets.QAction(MainWindow)
        self.actionAbout_Us.setObjectName("actionAbout_Us")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAccesibility = QtWidgets.QAction(MainWindow)
        self.actionAccesibility.setObjectName("actionAccesibility")
        self.actionSave_image = QtWidgets.QAction(MainWindow)
        self.actionSave_image.setObjectName("actionSave_image")
        self.actionRecord_video = QtWidgets.QAction(MainWindow)
        self.actionRecord_video.setCheckable(True)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("icon/Record_start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecord_video.setIcon(icon16)
        self.actionRecord_video.setObjectName("actionRecord_video")
        self.actionMaximized = QtWidgets.QAction(MainWindow)
        self.actionMaximized.setObjectName("actionMaximized")
        self.actionMinimized = QtWidgets.QAction(MainWindow)
        self.actionMinimized.setObjectName("actionMinimized")
        self.actionRotate_left = QtWidgets.QAction(MainWindow)
        self.actionRotate_left.setObjectName("actionRotate_left")
        self.actionRotatevright = QtWidgets.QAction(MainWindow)
        self.actionRotatevright.setObjectName("actionRotatevright")
        self.actionZoom_in = QtWidgets.QAction(MainWindow)
        self.actionZoom_in.setObjectName("actionZoom_in")
        self.actionZoom_out = QtWidgets.QAction(MainWindow)
        self.actionZoom_out.setObjectName("actionZoom_out")
        self.menuFile.addAction(self.actionOpen_Image)
        self.menuFile.addAction(self.actionLoad_Video)
        self.menuFile.addAction(self.actionOpen_Camera)
        self.menuFile.addAction(self.actionCam_parameter)
        self.menuFile.addAction(self.actionSave_image)
        self.menuFile.addAction(self.actionRecord_video)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout_Us)
        self.menuHelp.addAction(self.actionAccesibility)
        self.menuWindow.addAction(self.actionMinimized)
        self.menuWindow.addAction(self.actionMaximized)
        self.menuView.addAction(self.actionRotate_left)
        self.menuView.addAction(self.actionRotatevright)
        self.menuView.addAction(self.actionZoom_in)
        self.menuView.addAction(self.actionZoom_out)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Multi View"))
        self.btn_open_image.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.btn_open_camera.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.coombo_zoom.setItemText(0, _translate("MainWindow", "25%"))
        self.coombo_zoom.setItemText(1, _translate("MainWindow", "50%"))
        self.coombo_zoom.setItemText(2, _translate("MainWindow", "75%"))
        self.coombo_zoom.setItemText(3, _translate("MainWindow", "100%"))
        self.coombo_zoom.setItemText(4, _translate("MainWindow", "125%"))
        self.coombo_zoom.setItemText(5, _translate("MainWindow", "150%"))
        self.coombo_zoom.setItemText(6, _translate("MainWindow", "175%"))
        self.coombo_zoom.setItemText(7, _translate("MainWindow", "200%"))
        self.label_camera.setText(_translate("MainWindow", "Camera type: "))
        self.label_3.setText(_translate("MainWindow", "Saved Image"))
        self.title_image_ori.setText(_translate("MainWindow", "Image Ori"))
        self.label_12.setText(_translate("MainWindow", "6. Right Button View"))
        self.label_11.setText(_translate("MainWindow", "5. Bottom View"))
        self.label_7.setText(_translate("MainWindow", "1. Left view"))
        self.label_10.setText(_translate("MainWindow", "4. Left Button View"))
        self.label_9.setText(_translate("MainWindow", "3. Right View"))
        self.label_8.setText(_translate("MainWindow", "2. Center View"))
        self.btn_ori_view.setText(_translate("MainWindow", "Normal"))
        self.btn_ori_view.setShortcut(_translate("MainWindow", "N"))
        self.btn_6view.setText(_translate("MainWindow", "6-View"))
        self.btn_6view.setShortcut(_translate("MainWindow", "M"))
        self.btn_view_1.setText(_translate("MainWindow", "1"))
        self.btn_view_1.setShortcut(_translate("MainWindow", "1"))
        self.btn_view_2.setText(_translate("MainWindow", "2"))
        self.btn_view_2.setShortcut(_translate("MainWindow", "2"))
        self.btn_view_3.setText(_translate("MainWindow", "3"))
        self.btn_view_3.setShortcut(_translate("MainWindow", "3"))
        self.btn_view_4.setText(_translate("MainWindow", "4"))
        self.btn_view_4.setShortcut(_translate("MainWindow", "4"))
        self.btn_view_5.setText(_translate("MainWindow", "5"))
        self.btn_view_5.setShortcut(_translate("MainWindow", "5"))
        self.btn_view_6.setText(_translate("MainWindow", "6"))
        self.btn_view_6.setShortcut(_translate("MainWindow", "6"))
        self.btn_prev_video.setShortcut(_translate("MainWindow", "Left"))
        self.btn_play_pouse.setShortcut(_translate("MainWindow", "Space"))
        self.btn_stop_video.setShortcut(_translate("MainWindow", "S"))
        self.btn_skip_video.setShortcut(_translate("MainWindow", "Right"))
        self.label_time_recent.setText(_translate("MainWindow", "00.00"))
        self.label_time_end.setText(_translate("MainWindow", "00.00"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionOpen_Image.setText(_translate("MainWindow", "Open Image"))
        self.actionLoad_Video.setText(_translate("MainWindow", "Load Video"))
        self.actionOpen_Camera.setText(_translate("MainWindow", "Open Camera"))
        self.actionCam_parameter.setText(_translate("MainWindow", "Cam parameter"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout_Us.setText(_translate("MainWindow", "About Us"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAccesibility.setText(_translate("MainWindow", "Accesibility"))
        self.actionSave_image.setText(_translate("MainWindow", "Save image"))
        self.actionRecord_video.setText(_translate("MainWindow", "Record Video"))
        self.actionMaximized.setText(_translate("MainWindow", "Maximized"))
        self.actionMinimized.setText(_translate("MainWindow", "Minimized"))
        self.actionRotate_left.setText(_translate("MainWindow", "Rotate left"))
        self.actionRotatevright.setText(_translate("MainWindow", "Rotatevright"))
        self.actionZoom_in.setText(_translate("MainWindow", "Zoom in"))
        self.actionZoom_out.setText(_translate("MainWindow", "Zoom out"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

