# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_second_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogSecondWindow(object):
    def setupUi(self, DialogSecondWindow):
        DialogSecondWindow.setObjectName("DialogSecondWindow")
        DialogSecondWindow.resize(766, 531)
        self.label_second_window = QtWidgets.QLabel(DialogSecondWindow)
        self.label_second_window.setGeometry(QtCore.QRect(190, 170, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_second_window.setFont(font)
        self.label_second_window.setAlignment(QtCore.Qt.AlignCenter)
        self.label_second_window.setObjectName("label_second_window")
        self.label_data = QtWidgets.QLabel(DialogSecondWindow)
        self.label_data.setGeometry(QtCore.QRect(110, 310, 551, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_data.setFont(font)
        self.label_data.setAlignment(QtCore.Qt.AlignCenter)
        self.label_data.setObjectName("label_data")

        self.retranslateUi(DialogSecondWindow)
        QtCore.QMetaObject.connectSlotsByName(DialogSecondWindow)

    def retranslateUi(self, DialogSecondWindow):
        _translate = QtCore.QCoreApplication.translate
        DialogSecondWindow.setWindowTitle(_translate("DialogSecondWindow", "Second Window"))
        self.label_second_window.setText(_translate("DialogSecondWindow", "Second Window"))
        self.label_data.setText(_translate("DialogSecondWindow", "First window didn\'t set any Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogSecondWindow = QtWidgets.QDialog()
    ui = Ui_DialogSecondWindow()
    ui.setupUi(DialogSecondWindow)
    DialogSecondWindow.show()
    sys.exit(app.exec_())
