# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_first_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWinodwFirstWindow(object):
    def setupUi(self, MainWinodwFirstWindow):
        MainWinodwFirstWindow.setObjectName("MainWinodwFirstWindow")
        MainWinodwFirstWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWinodwFirstWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_moil_template = QtWidgets.QLabel(self.centralwidget)
        self.label_moil_template.setGeometry(QtCore.QRect(140, 80, 511, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_moil_template.setFont(font)
        self.label_moil_template.setAlignment(QtCore.Qt.AlignCenter)
        self.label_moil_template.setObjectName("label_moil_template")
        self.label_data = QtWidgets.QLabel(self.centralwidget)
        self.label_data.setGeometry(QtCore.QRect(230, 270, 67, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_data.setFont(font)
        self.label_data.setObjectName("label_data")
        self.lineedit_date = QtWidgets.QLineEdit(self.centralwidget)
        self.lineedit_date.setGeometry(QtCore.QRect(300, 270, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineedit_date.setFont(font)
        self.lineedit_date.setObjectName("lineedit_date")
        self.pushbtn_go = QtWidgets.QPushButton(self.centralwidget)
        self.pushbtn_go.setGeometry(QtCore.QRect(340, 400, 89, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushbtn_go.setFont(font)
        self.pushbtn_go.setObjectName("pushbtn_go")
        MainWinodwFirstWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWinodwFirstWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWinodwFirstWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWinodwFirstWindow)
        self.statusbar.setObjectName("statusbar")
        MainWinodwFirstWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWinodwFirstWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWinodwFirstWindow)

    def retranslateUi(self, MainWinodwFirstWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWinodwFirstWindow.setWindowTitle(_translate("MainWinodwFirstWindow", "First Window"))
        self.label_moil_template.setText(_translate("MainWinodwFirstWindow", "MoilApp - Tutorial Sample\n"
"\n"
"First Window"))
        self.label_data.setText(_translate("MainWinodwFirstWindow", "Data:"))
        self.lineedit_date.setPlaceholderText(_translate("MainWinodwFirstWindow", "Set second window\'s data here"))
        self.pushbtn_go.setText(_translate("MainWinodwFirstWindow", "Go !"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWinodwFirstWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWinodwFirstWindow()
    ui.setupUi(MainWinodwFirstWindow)
    MainWinodwFirstWindow.show()
    sys.exit(app.exec_())
