# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'template.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from moilutils.souceIcon import ResourceIcon


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        rs = ResourceIcon()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1806, 1024)
        MainWindow.showMaximized()
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_open_image = QtWidgets.QPushButton(self.frame_3)
        self.btn_open_image.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_open_image.setText("")
        iconOpenImage = QtGui.QIcon()
        iconOpenImage.addPixmap(QtGui.QPixmap.fromImage(rs.iconOpenImage()), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_open_image.setIcon(iconOpenImage)
        self.btn_open_image.setIconSize(QtCore.QSize(30, 30))
        self.btn_open_image.setObjectName("btn_open_image")
        self.horizontalLayout_5.addWidget(self.btn_open_image)
        self.btn_open_video = QtWidgets.QPushButton(self.frame_3)
        self.btn_open_video.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_open_video.setText("")
        iconOpenVideo = QtGui.QIcon()
        iconOpenVideo.addPixmap(QtGui.QPixmap.fromImage(rs.iconOpenVideo()), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_open_video.setIcon(iconOpenVideo)
        self.btn_open_video.setIconSize(QtCore.QSize(35, 30))
        self.btn_open_video.setObjectName("btn_open_video")
        self.horizontalLayout_5.addWidget(self.btn_open_video)
        self.btn_open_camera = QtWidgets.QPushButton(self.frame_3)
        self.btn_open_camera.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_open_camera.setText("")
        iconOpenCam = QtGui.QIcon()
        iconOpenCam.addPixmap(QtGui.QPixmap.fromImage(rs.iconOpenCam()), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_open_camera.setIcon(iconOpenCam)
        self.btn_open_camera.setIconSize(QtCore.QSize(30, 30))
        self.btn_open_camera.setObjectName("btn_open_camera")
        self.horizontalLayout_5.addWidget(self.btn_open_camera)
        self.btn_save_image = QtWidgets.QPushButton(self.frame_3)
        self.btn_save_image.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_save_image.setText("")
        iconSaveImg = QtGui.QIcon()
        iconSaveImg.addPixmap(QtGui.QPixmap.fromImage(rs.iconSaveImage()), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save_image.setIcon(iconSaveImg)
        self.btn_save_image.setIconSize(QtCore.QSize(40, 30))
        self.btn_save_image.setObjectName("btn_save_image")
        self.horizontalLayout_5.addWidget(self.btn_save_image)
        self.btn_Record_video = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Record_video.sizePolicy().hasHeightForWidth())
        self.btn_Record_video.setSizePolicy(sizePolicy)
        self.btn_Record_video.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_Record_video.setText("")
        iconRecord = QtGui.QIcon()
        iconRecord.addPixmap(QtGui.QPixmap.fromImage(rs.iconRecord()), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Record_video.setIcon(iconRecord)
        self.btn_Record_video.setIconSize(QtCore.QSize(30, 30))
        self.btn_Record_video.setCheckable(True)
        self.btn_Record_video.setObjectName("btn_Record_video")
        self.horizontalLayout_5.addWidget(self.btn_Record_video)
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.btn_rotate_left = QtWidgets.QPushButton(self.frame_3)
        self.btn_rotate_left.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_rotate_left.setText("")
        iconrotateLeft = QtGui.QIcon()
        iconrotateLeft.addPixmap(QtGui.QPixmap.fromImage(rs.iconRotateLeft()), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_rotate_left.setIcon(iconrotateLeft)
        self.btn_rotate_left.setIconSize(QtCore.QSize(40, 30))
        self.btn_rotate_left.setObjectName("btn_rotate_left")
        self.horizontalLayout_5.addWidget(self.btn_rotate_left)
        self.btn_rotate_right = QtWidgets.QPushButton(self.frame_3)
        self.btn_rotate_right.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_rotate_right.setText("")
        iconrotateRight = QtGui.QIcon()
        iconrotateRight.addPixmap(QtGui.QPixmap.fromImage(rs.iconRotateRight()), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_rotate_right.setIcon(iconrotateRight)
        self.btn_rotate_right.setIconSize(QtCore.QSize(40, 30))
        self.btn_rotate_right.setObjectName("btn_rotate_right")
        self.horizontalLayout_5.addWidget(self.btn_rotate_right)
        self.line_4 = QtWidgets.QFrame(self.frame_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_5.addWidget(self.line_4)
        self.btn_zoom_in = QtWidgets.QPushButton(self.frame_3)
        self.btn_zoom_in.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_zoom_in.setText("")
        iconZoomIn = QtGui.QIcon()
        iconZoomIn.addPixmap(QtGui.QPixmap.fromImage(rs.iconZoomIn()), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_zoom_in.setIcon(iconZoomIn)
        self.btn_zoom_in.setIconSize(QtCore.QSize(40, 30))
        self.btn_zoom_in.setObjectName("btn_zoom_in")
        self.horizontalLayout_5.addWidget(self.btn_zoom_in)
        self.btn_zoom_out = QtWidgets.QPushButton(self.frame_3)
        self.btn_zoom_out.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_zoom_out.setText("")
        iconZoomOut = QtGui.QIcon()
        iconZoomOut.addPixmap(QtGui.QPixmap.fromImage(rs.iconZoomOut()), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_zoom_out.setIcon(iconZoomOut)
        self.btn_zoom_out.setIconSize(QtCore.QSize(40, 30))
        self.btn_zoom_out.setObjectName("btn_zoom_out")
        self.horizontalLayout_5.addWidget(self.btn_zoom_out)
        self.coombo_zoom = QtWidgets.QComboBox(self.frame_3)
        self.coombo_zoom.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(12)
        self.coombo_zoom.setFont(font)
        self.coombo_zoom.setObjectName("coombo_zoom")
        self.coombo_zoom.addItem("")
        self.coombo_zoom.addItem("")
        self.coombo_zoom.addItem("")
        self.coombo_zoom.addItem("")
        self.coombo_zoom.addItem("")
        self.coombo_zoom.addItem("")
        self.coombo_zoom.addItem("")
        self.coombo_zoom.addItem("")
        self.horizontalLayout_5.addWidget(self.coombo_zoom)
        self.line_3 = QtWidgets.QFrame(self.frame_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_5.addWidget(self.line_3)
        self.label_camera = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_camera.sizePolicy().hasHeightForWidth())
        self.label_camera.setSizePolicy(sizePolicy)
        self.label_camera.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(14)
        self.label_camera.setFont(font)
        self.label_camera.setStyleSheet("")
        self.label_camera.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_camera.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_camera.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_camera.setObjectName("label_camera")
        self.horizontalLayout_5.addWidget(self.label_camera)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(920, 0))
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Panel)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1398, 816))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_result = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result.sizePolicy().hasHeightForWidth())
        self.label_result.setSizePolicy(sizePolicy)
        self.label_result.setMinimumSize(QtCore.QSize(900, 0))
        self.label_result.setMaximumSize(QtCore.QSize(16777215, 16777215))
        # self.label_result.setFrameShape(QtWidgets.QFrame.Box)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.horizontalLayout_7.addWidget(self.label_result, 0, QtCore.Qt.AlignHCenter)

        ########
        self.button_menu = QtWidgets.QPushButton(self.scrollArea)
        self.button_menu.setGeometry(QtCore.QRect(20, 15, 40, 30))
        self.button_menu.setStyleSheet(
            "QPushButton{\n"
            "  border-color: #71D1BA;\n"
            "  border-width: 2px;        \n"
            "  border-style: solid;\n"
            "  border-radius: 5px;\n"
            "}\n"
            "QPushButton::pressed{ background-color : #71AED1; }\n"
            "")
        self.button_menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap.fromImage(rs.iconMenu()),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off)
        self.button_menu.setIcon(icon)
        self.button_menu.setCheckable(True)
        self.button_menu.setChecked(False)
        self.button_menu.setIconSize(QtCore.QSize(40, 30))
        self.button_menu.setObjectName("button_menu")

        ##########
        self.frame_navigator = QtWidgets.QFrame(self.scrollArea)
        self.frame_navigator.setGeometry(QtCore.QRect(30, 40, 160, 290))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_navigator.sizePolicy().hasHeightForWidth())
        self.frame_navigator.setSizePolicy(sizePolicy)
        self.frame_navigator.setMinimumSize(QtCore.QSize(160, 160))
        self.frame_navigator.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_navigator.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_navigator.setLineWidth(0)
        self.frame_navigator.setObjectName("frame_navigator")
        self.frame_20 = QtWidgets.QFrame(self.frame_navigator)
        self.frame_20.setGeometry(QtCore.QRect(60, 10, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_20.sizePolicy().hasHeightForWidth())
        self.frame_20.setSizePolicy(sizePolicy)
        self.frame_20.setMinimumSize(QtCore.QSize(40, 40))
        self.frame_20.setStyleSheet("background-color: #71D1BA;   \n"
                                    "border-radius: 10px;")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.btn_Up_View = QtWidgets.QPushButton(self.frame_20)
        self.btn_Up_View.setGeometry(QtCore.QRect(0, 0, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Up_View.sizePolicy().hasHeightForWidth())
        self.btn_Up_View.setSizePolicy(sizePolicy)
        self.btn_Up_View.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_Up_View.setStyleSheet("QPushButton{ background-color :  #71D1BA;}\n"
                                       "QPushButton::pressed{ background-color : #71AED1; }\n"
                                       "border-radius: 10px;")
        self.btn_Up_View.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap.fromImage(rs.iconUp()), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Up_View.setIcon(icon)
        self.btn_Up_View.setIconSize(QtCore.QSize(40, 40))
        self.btn_Up_View.setObjectName("btn_Up_View")
        self.frame_21 = QtWidgets.QFrame(self.frame_navigator)
        self.frame_21.setGeometry(QtCore.QRect(110, 60, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_21.sizePolicy().hasHeightForWidth())
        self.frame_21.setSizePolicy(sizePolicy)
        self.frame_21.setMinimumSize(QtCore.QSize(40, 40))
        self.frame_21.setStyleSheet("background-color: #71D1BA;   \n"
                                    "border-radius: 10px;")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.btn_Right_view = QtWidgets.QPushButton(self.frame_21)
        self.btn_Right_view.setGeometry(QtCore.QRect(0, 0, 40, 40))
        self.btn_Right_view.setStyleSheet("QPushButton{ background-color :  #71D1BA;}\n"
                                          "QPushButton::pressed{ background-color : #71AED1; }\n"
                                          "border-radius: 10px;")
        self.btn_Right_view.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap.fromImage(rs.iconRight()), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Right_view.setIcon(icon1)
        self.btn_Right_view.setIconSize(QtCore.QSize(40, 40))
        self.btn_Right_view.setObjectName("btn_Right_view")
        self.frame_22 = QtWidgets.QFrame(self.frame_navigator)
        self.frame_22.setGeometry(QtCore.QRect(10, 60, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_22.sizePolicy().hasHeightForWidth())
        self.frame_22.setSizePolicy(sizePolicy)
        self.frame_22.setMinimumSize(QtCore.QSize(40, 40))
        self.frame_22.setStyleSheet("background-color: #71D1BA;   \n"
                                    "border-radius: 10px;")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.btn_left_view = QtWidgets.QPushButton(self.frame_22)
        self.btn_left_view.setGeometry(QtCore.QRect(0, 0, 40, 40))
        self.btn_left_view.setStyleSheet("QPushButton{ background-color :  #71D1BA;}\n"
                                         "QPushButton::pressed{ background-color : #71AED1; }\n"
                                         "border-radius: 10px;")
        self.btn_left_view.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap.fromImage(rs.iconLeft()), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_left_view.setIcon(icon2)
        self.btn_left_view.setIconSize(QtCore.QSize(40, 40))
        self.btn_left_view.setObjectName("btn_left_view")
        self.frame_23 = QtWidgets.QFrame(self.frame_navigator)
        self.frame_23.setGeometry(QtCore.QRect(60, 110, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_23.sizePolicy().hasHeightForWidth())
        self.frame_23.setSizePolicy(sizePolicy)
        self.frame_23.setMinimumSize(QtCore.QSize(40, 40))
        self.frame_23.setStyleSheet("background-color: #71D1BA;   \n"
                                    "border-radius: 10px;")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.btn_Down_view = QtWidgets.QPushButton(self.frame_23)
        self.btn_Down_view.setGeometry(QtCore.QRect(0, 0, 40, 40))
        self.btn_Down_view.setStyleSheet("QPushButton{ background-color :  #71D1BA;}\n"
                                         "QPushButton::pressed{ background-color : #71AED1; }\n"
                                         "border-radius: 10px;")
        self.btn_Down_view.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap.fromImage(rs.iconDown()), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Down_view.setIcon(icon3)
        self.btn_Down_view.setIconSize(QtCore.QSize(40, 40))
        self.btn_Down_view.setObjectName("btn_Down_view")
        self.frame_24 = QtWidgets.QFrame(self.frame_navigator)
        self.frame_24.setGeometry(QtCore.QRect(60, 60, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_24.sizePolicy().hasHeightForWidth())
        self.frame_24.setSizePolicy(sizePolicy)
        self.frame_24.setMinimumSize(QtCore.QSize(40, 40))
        self.frame_24.setStyleSheet("background-color: #71D1BA;   \n"
                                    "border-radius: 10px;")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.btn_center_view = QtWidgets.QPushButton(self.frame_24)
        self.btn_center_view.setGeometry(QtCore.QRect(0, 0, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_center_view.sizePolicy().hasHeightForWidth())
        self.btn_center_view.setSizePolicy(sizePolicy)
        self.btn_center_view.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_center_view.setStyleSheet("QPushButton{ background-color :  #71D1BA;}\n"
                                           "QPushButton::pressed{ background-color : #71AED1; }\n"
                                           "border-radius: 10px;")
        self.btn_center_view.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap.fromImage(rs.iconCenter()), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_center_view.setIcon(icon4)
        self.btn_center_view.setIconSize(QtCore.QSize(30, 40))
        self.btn_center_view.setObjectName("btn_center_view")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.frame_navigator)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 160, 161, 27))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_mode = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(12)
        self.label_mode.setFont(font)
        self.label_mode.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_mode.setObjectName("label_mode")
        self.horizontalLayout_4.addWidget(self.label_mode)
        self.radio_btn_mode_1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radio_btn_mode_1.setMinimumSize(QtCore.QSize(35, 0))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(12)
        self.radio_btn_mode_1.setFont(font)
        self.radio_btn_mode_1.setObjectName("radio_btn_mode_1")
        self.horizontalLayout_4.addWidget(self.radio_btn_mode_1)
        self.radio_btn_mode_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radio_btn_mode_2.setMinimumSize(QtCore.QSize(35, 0))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(12)
        self.radio_btn_mode_2.setFont(font)
        self.radio_btn_mode_2.setObjectName("radio_btn_mode_2")
        self.horizontalLayout_4.addWidget(self.radio_btn_mode_2)

        self.frame_panorama = QtWidgets.QFrame(self.scrollArea)
        self.frame_panorama.setGeometry(QtCore.QRect(20, 40, 200, 80))
        self.frame_panorama.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_panorama.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_panorama.setObjectName("frame_panorama")
        self.max_pano = QtWidgets.QSpinBox(self.frame_panorama)
        self.max_pano.setGeometry(QtCore.QRect(80, 10, 65, 30))
        self.max_pano.setMinimum(50)
        self.max_pano.setMaximum(110)
        self.max_pano.setSingleStep(1)
        self.max_pano.setObjectName("max_pano")
        self.max = QtWidgets.QLabel(self.frame_panorama)
        self.max.setGeometry(QtCore.QRect(10, 10, 70, 30))
        self.max.setObjectName("max")
        self.min_pano = QtWidgets.QSpinBox(self.frame_panorama)
        self.min_pano.setGeometry(QtCore.QRect(80, 45, 65, 30))
        self.min_pano.setMinimum(10)
        self.min_pano.setMaximum(100)
        self.min_pano.setSingleStep(1)
        self.min_pano.setObjectName("min_pano")
        self.min = QtWidgets.QLabel(self.frame_panorama)
        self.min.setGeometry(QtCore.QRect(10, 45, 70, 30))
        self.min.setObjectName("min")
        # self.pushButton = QtWidgets.QPushButton(self.frame_panorama)
        # self.pushButton.setGeometry(QtCore.QRect(150, 15, 50, 54))
        # self.pushButton.setText("")
        # self.pushButton.setIcon(icon6)
        # self.pushButton.setIconSize(QtCore.QSize(40, 40))
        # self.pushButton.setObjectName("pushButton")

        ###########################################

        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title_image_ori = QtWidgets.QLabel(self.frame_4)
        self.title_image_ori.setMinimumSize(QtCore.QSize(0, 40))
        self.title_image_ori.setMaximumSize(QtCore.QSize(16666777, 40))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(16)
        self.title_image_ori.setFont(font)
        self.title_image_ori.setStyleSheet("background-color: #71D1BA;   ")
        self.title_image_ori.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_image_ori.setAlignment(QtCore.Qt.AlignCenter)
        self.title_image_ori.setObjectName("title_image_ori")
        self.verticalLayout_2.addWidget(self.title_image_ori)
        self.label_ori = QtWidgets.QLabel(self.frame_4)
        self.label_ori.setMinimumSize(QtCore.QSize(0, 270))
        self.label_ori.setFrameShape(QtWidgets.QFrame.Box)
        self.label_ori.setText("")
        self.label_ori.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ori.setObjectName("label_ori")
        self.verticalLayout_2.addWidget(self.label_ori)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: #71D1BA;   \n"
                                   "border-radius: 10px;")
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.listWidget = QtWidgets.QListWidget(self.frame_4)
        # self.listWidget.setMinimumSize(QtCore.QSize(0, 400))
        self.listWidget.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        # spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        # self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_view = QtWidgets.QFrame(self.centralwidget)
        self.frame_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_view.setObjectName("frame_view")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_view)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_normal = QtWidgets.QPushButton(self.frame_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_normal.sizePolicy().hasHeightForWidth())
        self.btn_normal.setSizePolicy(sizePolicy)
        self.btn_normal.setMinimumSize(QtCore.QSize(60, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(12)
        self.btn_normal.setFont(font)
        self.btn_normal.setCheckable(True)
        self.btn_normal.setObjectName("btn_normal")
        self.horizontalLayout_4.addWidget(self.btn_normal)
        self.btn_anypoint = QtWidgets.QPushButton(self.frame_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_anypoint.sizePolicy().hasHeightForWidth())
        self.btn_anypoint.setSizePolicy(sizePolicy)
        self.btn_anypoint.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(12)
        self.btn_anypoint.setFont(font)
        self.btn_anypoint.setCheckable(True)
        self.btn_anypoint.setObjectName("btn_anypoint")
        self.horizontalLayout_4.addWidget(self.btn_anypoint)
        self.btn_panorama = QtWidgets.QPushButton(self.frame_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_panorama.sizePolicy().hasHeightForWidth())
        self.btn_panorama.setSizePolicy(sizePolicy)
        self.btn_panorama.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(12)
        self.btn_panorama.setFont(font)
        self.btn_panorama.setCheckable(True)
        self.btn_panorama.setObjectName("btn_panorama")
        self.horizontalLayout_4.addWidget(self.btn_panorama)
        self.horizontalLayout.addWidget(self.frame_view)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_prev_video = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_prev_video.sizePolicy().hasHeightForWidth())
        self.btn_prev_video.setSizePolicy(sizePolicy)
        self.btn_prev_video.setMinimumSize(QtCore.QSize(40, 30))
        self.btn_prev_video.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap.fromImage(rs.iconBackward()), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_prev_video.setIcon(icon9)
        self.btn_prev_video.setIconSize(QtCore.QSize(30, 30))
        self.btn_prev_video.setObjectName("btn_prev_video")
        self.horizontalLayout_6.addWidget(self.btn_prev_video)
        self.btn_play_pouse = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_play_pouse.sizePolicy().hasHeightForWidth())
        self.btn_play_pouse.setSizePolicy(sizePolicy)
        self.btn_play_pouse.setMinimumSize(QtCore.QSize(40, 30))
        self.btn_play_pouse.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap.fromImage(rs.iconPlay()), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_play_pouse.setIcon(icon10)
        self.btn_play_pouse.setIconSize(QtCore.QSize(30, 30))
        self.btn_play_pouse.setObjectName("btn_play_pouse")
        self.horizontalLayout_6.addWidget(self.btn_play_pouse)
        self.btn_stop_video = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_stop_video.sizePolicy().hasHeightForWidth())
        self.btn_stop_video.setSizePolicy(sizePolicy)
        self.btn_stop_video.setMinimumSize(QtCore.QSize(40, 30))
        self.btn_stop_video.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap.fromImage(rs.iconStop()), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_stop_video.setIcon(icon11)
        self.btn_stop_video.setIconSize(QtCore.QSize(30, 30))
        self.btn_stop_video.setObjectName("btn_stop_video")
        self.horizontalLayout_6.addWidget(self.btn_stop_video)
        self.btn_skip_video = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_skip_video.sizePolicy().hasHeightForWidth())
        self.btn_skip_video.setSizePolicy(sizePolicy)
        self.btn_skip_video.setMinimumSize(QtCore.QSize(40, 30))
        self.btn_skip_video.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap.fromImage(rs.iconForward()), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_skip_video.setIcon(icon12)
        self.btn_skip_video.setIconSize(QtCore.QSize(30, 30))
        self.btn_skip_video.setObjectName("btn_skip_video")
        self.horizontalLayout_6.addWidget(self.btn_skip_video)
        self.label_time_recent = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_recent.sizePolicy().hasHeightForWidth())
        self.label_time_recent.setSizePolicy(sizePolicy)
        self.label_time_recent.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(14)
        self.label_time_recent.setFont(font)
        self.label_time_recent.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_recent.setObjectName("label_time_recent")
        self.horizontalLayout_6.addWidget(self.label_time_recent)
        self.slider_Video = QtWidgets.QSlider(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_Video.sizePolicy().hasHeightForWidth())
        self.slider_Video.setSizePolicy(sizePolicy)
        self.slider_Video.setOrientation(QtCore.Qt.Horizontal)
        self.slider_Video.setObjectName("slider_Video")
        self.horizontalLayout_6.addWidget(self.slider_Video)
        self.label_time_end = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_end.sizePolicy().hasHeightForWidth())
        self.label_time_end.setSizePolicy(sizePolicy)
        self.label_time_end.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(14)
        self.label_time_end.setFont(font)
        self.label_time_end.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_end.setObjectName("label_time_end")
        self.horizontalLayout_6.addWidget(self.label_time_end)
        spacerItem5 = QtWidgets.QSpacerItem(450, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1806, 30))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(16)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(12)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(12)
        self.menuHelp.setFont(font)
        self.menuHelp.setObjectName("menuHelp")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_Image = QtWidgets.QAction(MainWindow)
        self.actionOpen_Image.setIcon(iconOpenImage)
        self.actionOpen_Image.setObjectName("actionOpen_Image")
        self.actionLoad_Video = QtWidgets.QAction(MainWindow)
        self.actionLoad_Video.setIcon(iconOpenVideo)
        self.actionLoad_Video.setObjectName("actionLoad_Video")
        self.actionOpen_Camera = QtWidgets.QAction(MainWindow)
        self.actionOpen_Camera.setIcon(iconOpenCam)
        self.actionOpen_Camera.setObjectName("actionOpen_Camera")
        self.actionCam_parameter = QtWidgets.QAction(MainWindow)
        self.actionCam_parameter.setObjectName("actionCam_parameter")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout_Us = QtWidgets.QAction(MainWindow)
        self.actionAbout_Us.setObjectName("actionAbout_Us")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAccesibility = QtWidgets.QAction(MainWindow)
        self.actionAccesibility.setObjectName("actionAccesibility")
        self.actionSave_image = QtWidgets.QAction(MainWindow)
        self.actionSave_image.setObjectName("actionSave_image")
        self.actionRecord_video = QtWidgets.QAction(MainWindow)
        self.actionRecord_video.setCheckable(True)
        self.actionRecord_video.setIcon(iconRecord)
        self.actionRecord_video.setObjectName("actionRecord_video")
        self.actionMaximized = QtWidgets.QAction(MainWindow)
        self.actionMaximized.setObjectName("actionMaximized")
        self.actionMinimized = QtWidgets.QAction(MainWindow)
        self.actionMinimized.setObjectName("actionMinimized")
        self.actionRotate_left = QtWidgets.QAction(MainWindow)
        self.actionRotate_left.setObjectName("actionRotate_left")
        self.actionRotatevright = QtWidgets.QAction(MainWindow)
        self.actionRotatevright.setObjectName("actionRotatevright")
        self.actionZoom_in = QtWidgets.QAction(MainWindow)
        self.actionZoom_in.setObjectName("actionZoom_in")
        self.actionZoom_out = QtWidgets.QAction(MainWindow)
        self.actionZoom_out.setObjectName("actionZoom_out")
        self.menuFile.addAction(self.actionOpen_Image)
        self.menuFile.addAction(self.actionLoad_Video)
        self.menuFile.addAction(self.actionOpen_Camera)
        self.menuFile.addAction(self.actionCam_parameter)
        self.menuFile.addAction(self.actionSave_image)
        self.menuFile.addAction(self.actionRecord_video)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout_Us)
        self.menuHelp.addAction(self.actionAccesibility)
        self.menuWindow.addAction(self.actionMinimized)
        self.menuWindow.addAction(self.actionMaximized)
        self.menuView.addAction(self.actionRotate_left)
        self.menuView.addAction(self.actionRotatevright)
        self.menuView.addAction(self.actionZoom_in)
        self.menuView.addAction(self.actionZoom_out)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Template"))
        self.btn_open_image.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.btn_open_video.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.btn_open_camera.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.coombo_zoom.setItemText(0, _translate("MainWindow", "25%"))
        self.coombo_zoom.setItemText(1, _translate("MainWindow", "50%"))
        self.coombo_zoom.setItemText(2, _translate("MainWindow", "75%"))
        self.coombo_zoom.setItemText(3, _translate("MainWindow", "100%"))
        self.coombo_zoom.setItemText(4, _translate("MainWindow", "125%"))
        self.coombo_zoom.setItemText(5, _translate("MainWindow", "150%"))
        self.coombo_zoom.setItemText(6, _translate("MainWindow", "175%"))
        self.coombo_zoom.setItemText(7, _translate("MainWindow", "200%"))
        self.label_camera.setText(_translate("MainWindow", "Camera type: "))
        self.title_image_ori.setText(_translate("MainWindow", "Image Ori"))
        self.label_3.setText(_translate("MainWindow", "Saved Image"))
        self.btn_normal.setText(_translate("MainWindow", "Normal"))
        self.btn_normal.setShortcut(_translate("MainWindow", "N"))
        self.btn_anypoint.setText(_translate("MainWindow", "Anypoint"))
        self.btn_anypoint.setShortcut(_translate("MainWindow", "A"))
        self.btn_panorama.setText(_translate("MainWindow", "Panorama"))
        self.btn_panorama.setShortcut(_translate("MainWindow", "P"))
        self.btn_prev_video.setShortcut(_translate("MainWindow", "Left"))
        self.btn_play_pouse.setShortcut(_translate("MainWindow", "Space"))
        self.btn_stop_video.setShortcut(_translate("MainWindow", "S"))
        self.btn_skip_video.setShortcut(_translate("MainWindow", "Right"))
        self.label_time_recent.setText(_translate("MainWindow", "00.00"))
        self.label_time_end.setText(_translate("MainWindow", "00.00"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionOpen_Image.setText(_translate("MainWindow", "Open Image"))
        self.actionLoad_Video.setText(_translate("MainWindow", "Load Video"))
        self.actionOpen_Camera.setText(_translate("MainWindow", "Open Camera"))
        self.actionCam_parameter.setText(_translate("MainWindow", "Cam parameter"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout_Us.setText(_translate("MainWindow", "About Us"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAccesibility.setText(_translate("MainWindow", "Accessibility"))
        self.actionSave_image.setText(_translate("MainWindow", "Save image"))
        self.actionRecord_video.setText(_translate("MainWindow", "Record Video"))
        self.actionMaximized.setText(_translate("MainWindow", "Maximized"))
        self.actionMinimized.setText(_translate("MainWindow", "Minimized"))
        self.actionRotate_left.setText(_translate("MainWindow", "Rotate left"))
        self.actionRotatevright.setText(_translate("MainWindow", "Rotate right"))
        self.actionZoom_in.setText(_translate("MainWindow", "Zoom in"))
        self.actionZoom_out.setText(_translate("MainWindow", "Zoom out"))

        self.label_mode.setText(_translate("MainWindow", "Mode:"))
        self.radio_btn_mode_1.setText(_translate("MainWindow", "1"))
        self.radio_btn_mode_2.setText(_translate("MainWindow", "2"))
        self.max.setText(_translate("MainWindow", "Max Fov :"))
        self.min.setText(_translate("MainWindow", "Min Fov :"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

