# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(863, 671)
        self.frame_panorama = QtWidgets.QFrame(Form)
        self.frame_panorama.setGeometry(QtCore.QRect(220, 230, 161, 191))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(13)
        self.frame_panorama.setFont(font)
        self.frame_panorama.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_panorama.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_panorama.setObjectName("frame_panorama")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_panorama)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.frame_panorama)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelIcx = QtWidgets.QLabel(self.frame_panorama)
        self.labelIcx.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(13)
        self.labelIcx.setFont(font)
        self.labelIcx.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.labelIcx.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelIcx.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelIcx.setObjectName("labelIcx")
        self.gridLayout.addWidget(self.labelIcx, 0, 0, 1, 1)
        self.setIcy = QtWidgets.QSpinBox(self.frame_panorama)
        self.setIcy.setMinimumSize(QtCore.QSize(0, 30))
        self.setIcy.setObjectName("setIcy")
        self.gridLayout.addWidget(self.setIcy, 1, 1, 1, 1)
        self.max_pano = QtWidgets.QSpinBox(self.frame_panorama)
        self.max_pano.setMinimumSize(QtCore.QSize(0, 30))
        self.max_pano.setObjectName("max_pano")
        self.gridLayout.addWidget(self.max_pano, 2, 1, 1, 1)
        self.setIcx = QtWidgets.QSpinBox(self.frame_panorama)
        self.setIcx.setMinimumSize(QtCore.QSize(0, 30))
        self.setIcx.setObjectName("setIcx")
        self.gridLayout.addWidget(self.setIcx, 0, 1, 1, 1)
        self.labelMax = QtWidgets.QLabel(self.frame_panorama)
        self.labelMax.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(13)
        self.labelMax.setFont(font)
        self.labelMax.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.labelMax.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelMax.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelMax.setObjectName("labelMax")
        self.gridLayout.addWidget(self.labelMax, 2, 0, 1, 1)
        self.labelIcy = QtWidgets.QLabel(self.frame_panorama)
        self.labelIcy.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(13)
        self.labelIcy.setFont(font)
        self.labelIcy.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.labelIcy.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelIcy.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelIcy.setObjectName("labelIcy")
        self.gridLayout.addWidget(self.labelIcy, 1, 0, 1, 1)
        self.labelMin = QtWidgets.QLabel(self.frame_panorama)
        self.labelMin.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(13)
        self.labelMin.setFont(font)
        self.labelMin.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.labelMin.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelMin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelMin.setObjectName("labelMin")
        self.gridLayout.addWidget(self.labelMin, 3, 0, 1, 1)
        self.min_pano = QtWidgets.QSpinBox(self.frame_panorama)
        self.min_pano.setMinimumSize(QtCore.QSize(0, 30))
        self.min_pano.setObjectName("min_pano")
        self.gridLayout.addWidget(self.min_pano, 3, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox.setText(_translate("Form", "Auto Recenter"))
        self.labelIcx.setText(_translate("Form", "Center X:"))
        self.labelMax.setText(_translate("Form", "Max FoV:"))
        self.labelIcy.setText(_translate("Form", "Center Y:"))
        self.labelMin.setText(_translate("Form", "Min FoV:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

